name: Build and Publish Docker Image

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: Organograma
    
    permissions:
      contents: read
      packages: write

    steps:
      - name: Verificar secrets
        run: |
          [ -n "${{ secrets.VITE_ORGANOGRAMA_API_URL }}" ] && echo "API URL OK" || (echo "API URL vazia" && exit 1)
          [ -n "${{ secrets.VITE_N8N_HEADER }}" ] && echo "HEADER OK" || (echo "HEADER vazio" && exit 1)

      - name: Checkout
        uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/artlimp-brasil/organogramaempresa
          tags: |
            type=raw,value=latest
            type=sha

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          build-args: |
            VITE_ORGANOGRAMA_API_URL=${{ secrets.VITE_ORGANOGRAMA_API_URL }}
            VITE_N8N_HEADER=${{ secrets.VITE_N8N_HEADER }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}